# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AAFingerprint' do


end

target 'AAFingerprintDemo' do

    pod 'AAFingerprint', :path => '.'

end
